# Generated by Django 6.1.1 on 2026-09-05 12:17

import chores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='invite_code',
            field=models.CharField(default=chores.models.generate_invite_code, max_length=20, unique=True),
        ),
    ]
